### ISSUE TITLE
function Mix.env/0 is undefined (module Mix is not available)

### ISSUE THREAD

**Issue by xieyunzi** [BlakeWilliams/envy#6]
see here
https://github.com/honeybadger-io/honeybadger-elixir/issues/8

i use `exrm` release my app, it can't work

**Comment by BlakeWilliams** [comment]
Can you share code or elaborate on how you're running into this error?

**Comment by BlakeWilliams** [comment]
Closing because there's not enough detail here to do anything.

**Comment by punitcse** [comment]
@BlakeWilliams I am trying to build release using the following command 

```
$ mix release
 ```
and getting following error. I tried to refer this issue #4 but could not get any success.

```
[info] Application envy exited: exited in: Envy.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function Mix.env/0 is undefined (module Mix is not available)
            Mix.env()
            (envy) lib/envy.ex:37: Envy.auto_load/0
            (envy) lib/envy.ex:7: Envy.start/2
            (kernel) application_master.erl:273: :application_master.start_it_old/4
{"Kernel pid terminated",application_controller,"{application_start_failure,envy,{bad_return,{{'Elixir.Envy',start,[normal,[]]},{'EXIT',{undef,[{'Elixir.Mix',env,[],[]},{'Elixir.Envy',auto_load,0,[{file,\"lib/envy.ex\"},{line,37}]},{'Elixir.Envy',start,2,[{file,\"lib/envy.ex\"},{line,7}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,273}]}]}}}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,envy,{bad_return,{{'Elixir.Envy',start,[normal,[]]},{'EXIT',{undef,[{'Elixir.Mix',env,[],[]},{'Elixir.Envy',auto_load,0,[{fil
```

Any suggestion is appricated
